"""
CDA API

API definition for the CDA  # noqa: E501

The version of the OpenAPI document: 2.1.0
Generated by: https://openapi-generator.tech
"""

import unittest


class TestRow(unittest.TestCase):
    """Row unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRow(self):
        """Test Row"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Row()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
