# coding: utf-8

"""
    CDA API

    API definition for the CDA  # noqa: E501

    The version of the OpenAPI document: 3.0.0
    Generated by: https://openapi-generator.tech
"""

import unittest

import cda_client
from cda_client.model.date_type import DateType
from cda_client import configuration


class TestDateType(unittest.TestCase):
    """DateType unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
