"""
    CDA API

    API definition for the CDA  # noqa: E501

    The version of the OpenAPI document: 3.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import cda_client
from cda_client.model.job_status_data import JobStatusData


class TestJobStatusData(unittest.TestCase):
    """JobStatusData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testJobStatusData(self):
        """Test JobStatusData"""
        # FIXME: construct object with mandatory attributes with example values
        # model = JobStatusData()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
