# coding: utf-8

"""
    CDA API

    API definition for the CDA  # noqa: E501

    The version of the OpenAPI document: 1.0.0-rc.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import cda_client
from cda_client.models.error_report import ErrorReport  # noqa: E501
from cda_client.rest import ApiException

class TestErrorReport(unittest.TestCase):
    """ErrorReport unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ErrorReport
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = cda_client.models.error_report.ErrorReport()  # noqa: E501
        if include_optional :
            return ErrorReport(
                message = '0', 
                status_code = 56, 
                causes = [
                    '0'
                    ]
            )
        else :
            return ErrorReport(
        )

    def testErrorReport(self):
        """Test ErrorReport"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
