"""
    CDA API

    API definition for the CDA  # noqa: E501

    The version of the OpenAPI document: 3.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import cda_client
from cda_client.model.error_report import ErrorReport


class TestErrorReport(unittest.TestCase):
    """ErrorReport unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testErrorReport(self):
        """Test ErrorReport"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ErrorReport()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
