"""
CDA API

API definition for the CDA  # noqa: E501

The version of the OpenAPI document: 3.0.0
Generated by: https://openapi-generator.tech
"""

import unittest


class TestColumnsResponseData(unittest.TestCase):
    """ColumnsResponseData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testColumnsResponseData(self):
        """Test ColumnsResponseData"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ColumnsResponseData()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
