# coding: utf-8

"""
    CDA API

    API definition for the CDA  # noqa: E501

    The version of the OpenAPI document: 1.0.0-rc.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import cda_client
from cda_client.models.model import Model  # noqa: E501
from cda_client.rest import ApiException

class TestModel(unittest.TestCase):
    """Model unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test Model
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = cda_client.models.model.Model()  # noqa: E501
        if include_optional :
            return Model(
                version = '0', 
                date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                model = cda_client.models.model.model()
            )
        else :
            return Model(
        )

    def testModel(self):
        """Test Model"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
