"""
    CDA API

    API definition for the CDA  # noqa: E501

    The version of the OpenAPI document: 3.0.0_RC
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import cda_client
from cda_client.model.system_status_systems import SystemStatusSystems


class TestSystemStatusSystems(unittest.TestCase):
    """SystemStatusSystems unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSystemStatusSystems(self):
        """Test SystemStatusSystems"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SystemStatusSystems()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
