"""
    CDA API

    API definition for the CDA  # noqa: E501

    The version of the OpenAPI document: 1.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import cda_client
from cda_client.model.query import Query


class TestQuery(unittest.TestCase):
    """Query unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testQuery(self):
        """Test Query"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Query()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
