"""
CDA API

API definition for the CDA  # noqa: E501

The version of the OpenAPI document: 3.0.0
Generated by: https://openapi-generator.tech
"""

import unittest


class TestQueryResponseData(unittest.TestCase):
    """QueryResponseData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testQueryResponseData(self):
        """Test QueryResponseData"""
        # FIXME: construct object with mandatory attributes with example values
        # model = QueryResponseData()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
