"""
    CDA API

    API definition for the CDA  # noqa: E501

    The version of the OpenAPI document: 1.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import cda_client
from cda_client.model.query_created_data import QueryCreatedData


class TestQueryCreatedData(unittest.TestCase):
    """QueryCreatedData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testQueryCreatedData(self):
        """Test QueryCreatedData"""
        # FIXME: construct object with mandatory attributes with example values
        # model = QueryCreatedData()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
