"""
    CDA API

    API definition for the CDA  # noqa: E501

    The version of the OpenAPI document: 3.0.0_RC
    Generated by: https://openapi-generator.tech
"""


import unittest

import cda_client
from cda_client.api.query_api import QueryApi  # noqa: E501


class TestQueryApi(unittest.TestCase):
    """QueryApi unit test stubs"""

    def setUp(self):
        self.api = QueryApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_boolean_query(self):
        """Test case for boolean_query

        Execute boolean query  # noqa: E501
        """
        pass

    def test_bulk_data(self):
        """Test case for bulk_data

        Return all data in CDA  # noqa: E501
        """
        pass

    def test_columns(self):
        """Test case for columns

        Returns all column names  # noqa: E501
        """
        pass

    def test_diagnosis_counts_query(self):
        """Test case for diagnosis_counts_query

        Execute Diagnosis Counts query  # noqa: E501
        """
        pass

    def test_diagnosis_query(self):
        """Test case for diagnosis_query

        Execute Diagnosis query  # noqa: E501
        """
        pass

    def test_files(self):
        """Test case for files

        Returns a list of files given a boolean query  # noqa: E501
        """
        pass

    def test_global_counts(self):
        """Test case for global_counts

        Returns counts of the DCS  # noqa: E501
        """
        pass

    def test_job_status(self):
        """Test case for job_status

        Return the running status of long running queries.  # noqa: E501
        """
        pass

    def test_query(self):
        """Test case for query

        Given a query ID, return the a page of data from the query result.  # noqa: E501
        """
        pass

    def test_research_subject_counts_query(self):
        """Test case for research_subject_counts_query

        Execute ResearchSubjects Counts query  # noqa: E501
        """
        pass

    def test_research_subject_files_query(self):
        """Test case for research_subject_files_query

        Execute ResearchSubject Files query  # noqa: E501
        """
        pass

    def test_research_subject_query(self):
        """Test case for research_subject_query

        Execute Research Subject query  # noqa: E501
        """
        pass

    def test_specimen_counts_query(self):
        """Test case for specimen_counts_query

        Execute Specimen Counts query  # noqa: E501
        """
        pass

    def test_specimen_files_query(self):
        """Test case for specimen_files_query

        Execute Specimen Files query  # noqa: E501
        """
        pass

    def test_specimen_query(self):
        """Test case for specimen_query

        Execute Specimens query  # noqa: E501
        """
        pass

    def test_sql_query(self):
        """Test case for sql_query

        Execute SQL directly on a version of the dataset  # noqa: E501
        """
        pass

    def test_subject_counts_query(self):
        """Test case for subject_counts_query

        Execute Subjects Counts query  # noqa: E501
        """
        pass

    def test_subject_files_query(self):
        """Test case for subject_files_query

        Execute Subject Files query  # noqa: E501
        """
        pass

    def test_subject_query(self):
        """Test case for subject_query

        Execute Subject query  # noqa: E501
        """
        pass

    def test_treatment_counts_query(self):
        """Test case for treatment_counts_query

        Execute Treatments Counts query  # noqa: E501
        """
        pass

    def test_treatments_query(self):
        """Test case for treatments_query

        Execute Treatments query  # noqa: E501
        """
        pass

    def test_unique_values(self):
        """Test case for unique_values

        Returns all unique values  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
